version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=ddd-gym
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
